maintenance: off #This is if the maintenance option is enabled (set to 'on' to enable), BEWARE! ONLY OPs CAN JOIN IF ENABLED

serverName: MyServer!

commands:
  homes: true
  spawn: true
  tpa: true
  suicide: true
  headitem: true
  miniblock: true

dropPlayerHeadOnKill: true

tpa-keep-alive: 30 #in seconds
confupdate-stop: 30 #in seconds

enable1984: false
enable1984-path: /var/www/db/ravellogs/server

capes-path: /var/www/db/capes
